[package]
name = "yew-with-routing-trunk-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.6"
wasm-logger = "0.2.0"
yew-router = "0.16.0"
yew = "0.19"
